2025-05-20 16:14:50,341 Downloading and reading test artifact
[34m[1mwandb[39m[22m: [32m[41mERROR[39m[49m 'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "/opt/miniconda3/envs/mlflow-6ad30c7f773cc61dddb66fdbe8000959bdd76f06/lib/python3.9/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/opt/miniconda3/envs/mlflow-6ad30c7f773cc61dddb66fdbe8000959bdd76f06/lib/python3.9/site-packages/wandb/apis/public/api.py", line 958, in artifact
    artifact = wandb.Artifact._from_name(
  File "/opt/miniconda3/envs/mlflow-6ad30c7f773cc61dddb66fdbe8000959bdd76f06/lib/python3.9/site-packages/wandb/sdk/artifacts/artifact.py", line 252, in _from_name
    attrs = response.get("project", {}).get("artifact")
AttributeError: 'NoneType' object has no attribute 'get'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/amandaworker/Documents/Udacity/Machine Learning Engineer/reproducible_workflow/nd0821-c2-build-model-workflow-exercises-master/lesson-4-training-validation-experiment-tracking/exercises/exercise_10/starter/random_forest/run.py", line 228, in <module>
    go(args)
  File "/Users/amandaworker/Documents/Udacity/Machine Learning Engineer/reproducible_workflow/nd0821-c2-build-model-workflow-exercises-master/lesson-4-training-validation-experiment-tracking/exercises/exercise_10/starter/random_forest/run.py", line 29, in go
    train_data_path = run.use_artifact(args.train_data).file()
  File "/opt/miniconda3/envs/mlflow-6ad30c7f773cc61dddb66fdbe8000959bdd76f06/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 371, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/opt/miniconda3/envs/mlflow-6ad30c7f773cc61dddb66fdbe8000959bdd76f06/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 361, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/miniconda3/envs/mlflow-6ad30c7f773cc61dddb66fdbe8000959bdd76f06/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2783, in use_artifact
    artifact = public_api.artifact(type=type, name=name)
  File "/opt/miniconda3/envs/mlflow-6ad30c7f773cc61dddb66fdbe8000959bdd76f06/lib/python3.9/site-packages/wandb/apis/normalize.py", line 87, in wrapper
    raise CommError(message, err).with_traceback(sys.exc_info()[2])
  File "/opt/miniconda3/envs/mlflow-6ad30c7f773cc61dddb66fdbe8000959bdd76f06/lib/python3.9/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/opt/miniconda3/envs/mlflow-6ad30c7f773cc61dddb66fdbe8000959bdd76f06/lib/python3.9/site-packages/wandb/apis/public/api.py", line 958, in artifact
    artifact = wandb.Artifact._from_name(
  File "/opt/miniconda3/envs/mlflow-6ad30c7f773cc61dddb66fdbe8000959bdd76f06/lib/python3.9/site-packages/wandb/sdk/artifacts/artifact.py", line 252, in _from_name
    attrs = response.get("project", {}).get("artifact")
wandb.errors.CommError: 'NoneType' object has no attribute 'get'